### ISSUE TITLE
Build problems: execvp

### ISSUE THREAD

**Issue by dalb8** [tias/android-busybox-ndk#2] opened 2012-12-23 15:38 UTC
^^Title is wrong. I have a different problem now

I tried to build with the stericson config on ndk-r8c and I get the ether-wake error. I tried patching with patch -p1 < patch/023-ether-wake.patch but it didn't work: I didn't have the time to look into it further.

With config from busybox repo on ndk-r8b I get :`
  CC      networking/udhcp/common.o
  CC      networking/udhcp/dhcpc.o
networking/udhcp/dhcpc.c: In function 'udhcp_recv_raw_packet':
networking/udhcp/dhcpc.c:839:24: error: invalid application of 'sizeof' to incomplete type 'struct tpacket_auxdata' 
networking/udhcp/dhcpc.c:902:26: error: 'PACKET_AUXDATA' undeclared (first use in this function)
networking/udhcp/dhcpc.c:902:26: note: each undeclared identifier is reported only once for each function it appears in
networking/udhcp/dhcpc.c:909:11: error: dereferencing pointer to incomplete type
networking/udhcp/dhcpc.c:839:16: warning: unused variable 'cmsgbuf' [-Wunused-variable]
networking/udhcp/dhcpc.c: In function 'udhcp_raw_socket':
networking/udhcp/dhcpc.c:1035:33: error: 'PACKET_AUXDATA' undeclared (first use in this function)
make[1]: *** [networking/udhcp/dhcpc.o] Error 1
make: *** [networking/udhcp] Error 2
`
My motivation is that there are quite a few projects in the queue on F-Droid.org that have busybox blobs. We have built Busybox already as part of Lildebi (Guardian Project), but I'm not a programmer so I cant tell whats better, so I hope you can advise. I've added your repo and Busybox itself as srclibs for fdroidserver in the meantime.
I was using Makefile from Busybox repo.

 Sidenote: iptables is another important one; that was built with ndkr5 for Droidwall, but probably  needs tweaking.

**Comment by dalb8** [comment] 2013-01-20 15:27
It builds with https://github.com/tias/android-busybox-ndk/blob/master/android_ndk_defconfigPlus

**Comment by dalb8** [comment] 2013-01-23 19:01
OK, more news. I applied the following patches to busybox at c9677ed83c

 015-zcip.patch; 016-swapon-swapoff.patch; 022-ipv6.patch; 023-ether-wake.patch; 050-dietlibc_resolver-nslookup.patch

and with stericson config and ndk-r8b.

```
  CC      util-linux/volume_id/ext.o
  CC      util-linux/volume_id/fat.o
  CC      util-linux/volume_id/get_devname.o
  CC      util-linux/volume_id/hfs.o
  CC      util-linux/volume_id/iso9660.o
  CC      util-linux/volume_id/jfs.o
  CC      util-linux/volume_id/linux_raid.o
  CC      util-linux/volume_id/linux_swap.o
  CC      util-linux/volume_id/luks.o
  CC      util-linux/volume_id/ntfs.o
  CC      util-linux/volume_id/ocfs2.o
  CC      util-linux/volume_id/reiserfs.o
  CC      util-linux/volume_id/romfs.o
  CC      util-linux/volume_id/sysv.o
  CC      util-linux/volume_id/udf.o
  CC      util-linux/volume_id/util.o
  CC      util-linux/volume_id/volume_id.o
  CC      util-linux/volume_id/xfs.o
  AR      util-linux/volume_id/lib.a
  LINK    busybox_unstripped
Trying libraries: c dl gcc m
Failed: -Wl,--start-group -lc -ldl -lgcc -lm -Wl,--end-group
Output of:
arm-linux-androideabi-gcc -Wall -Wshadow -Wwrite-strings -Wundef -Wstrict-prototypes -Wunused -Wunused-parameter -Wunused-function -Wunused-value -Wmissing-prototypes -Wmissing-declarations -Wdeclaration-after-statement -Wold-style-definition -fno-builtin-strlen -finline-limit=0 -fomit-frame-pointer -ffunction-sections -fdata-sections -fno-guess-branch-probability -funsigned-char -static-libgcc -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -Os -DANDROID -D__ANDROID__ -DSK_RELEASE -nostdlib -march=armv7-a -msoft-float -mfloat-abi=softfp -mfpu=neon -mthumb -mthumb-interwork -fpic -fno-short-enums -fgcse-after-reload -frename-registers --sysroot=/home/gerry/android-ndk-r8b/platforms/android-9/arch-arm -Xlinker -z -Xlinker muldefs -nostdlib -Bdynamic -Xlinker -dynamic-linker -Xlinker /system/bin/linker -Xlinker -z -Xlinker nocopyreloc -Xlinker --no-undefined /home/gerry/android-ndk-r8b/platforms/android-9/arch-arm/usr/lib/crtbegin_dynamic.o /home/gerry/android-ndk-r8b/platforms/android-9/arch-arm/usr/lib/crtend_android.o -o busybox_unstripped -Wl,--start-group applets/built-in.o archival/lib.a archival/libarchive/lib.a console-tools/lib.a coreutils/lib.a coreutils/libcoreutils/lib.a debianutils/lib.a e2fsprogs/lib.a editors/lib.a findutils/lib.a init/lib.a libbb/lib.a libpwdgrp/lib.a libres/lib.a loginutils/lib.a mailutils/lib.a miscutils/lib.a modutils/lib.a networking/lib.a networking/libiproute/lib.a networking/udhcp/lib.a printutils/lib.a procps/lib.a runit/lib.a selinux/lib.a shell/lib.a sysklogd/lib.a util-linux/lib.a util-linux/volume_id/lib.a archival/built-in.o archival/libarchive/built-in.o console-tools/built-in.o coreutils/built-in.o coreutils/libcoreutils/built-in.o debianutils/built-in.o e2fsprogs/built-in.o editors/built-in.o findutils/built-in.o init/built-in.o libbb/built-in.o libpwdgrp/built-in.o libres/built-in.o loginutils/built-in.o mailutils/built-in.o miscutils/built-in.o modutils/built-in.o networking/built-in.o networking/libiproute/built-in.o networking/udhcp/built-in.o printutils/built-in.o procps/built-in.o runit/built-in.o selinux/built-in.o shell/built-in.o sysklogd/built-in.o util-linux/built-in.o util-linux/volume_id/built-in.o -Wl,--end-group -Wl,--start-group -lc -ldl -lgcc -lm -Wl,--end-group

/home/gerry/android-ndk-r8b/toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.4.3/../../../../arm-linux-androideabi/bin/ld: Warning: /home/gerry/android-ndk-r8b/platforms/android-9/arch-arm/usr/lib/crtend_android.o: Unknown EABI object attribute 44
miscutils/lib.a(microcom.o): In function `microcom_main':
microcom.c:(.text.microcom_main+0xdc): undefined reference to `cfsetspeed'
networking/lib.a(ether-wake.o): In function `ether_wake_main':
ether-wake.c:(.text.ether_wake_main+0xcc): undefined reference to `ether_aton_r'
networking/lib.a(nameif.o): In function `prepend_new_eth_table':
nameif.c:(.text.prepend_new_eth_table+0xd8): undefined reference to `ether_aton_r'
util-linux/lib.a(mount.o): In function `mount_main':
mount.c:(.text.mount_main+0xce): undefined reference to `setmntent'
mount.c:(.text.mount_main+0x114): undefined reference to `getmntent_r'
mount.c:(.text.mount_main+0x1a8): undefined reference to `setmntent'
mount.c:(.text.mount_main+0x21c): undefined reference to `getmntent_r'
util-linux/lib.a(swaponoff.o): In function `swap_enable_disable':
swaponoff.c:(.text.swap_enable_disable+0x5a): undefined reference to `swapon'
swaponoff.c:(.text.swap_enable_disable+0x62): undefined reference to `swapoff'
util-linux/lib.a(swaponoff.o): In function `swap_on_off_main':
swaponoff.c:(.text.swap_on_off_main+0x1c): undefined reference to `setmntent'
util-linux/lib.a(umount.o): In function `umount_main':
umount.c:(.text.umount_main+0x3e): undefined reference to `setmntent'
umount.c:(.text.umount_main+0x98): undefined reference to `getmntent_r'
umount.c:(.text.umount_main+0xa2): undefined reference to `endmntent'
coreutils/lib.a(df.o): In function `df_main':
df.c:(.text.df_main+0xbe): undefined reference to `setmntent'
df.c:(.text.df_main+0xf6): undefined reference to `endmntent'
e2fsprogs/lib.a(fsck.o): In function `fsck_main':
fsck.c:(.text.fsck_main+0x328): undefined reference to `setmntent'
fsck.c:(.text.fsck_main+0x35e): undefined reference to `getmntent_r'
fsck.c:(.text.fsck_main+0x368): undefined reference to `endmntent'
libbb/lib.a(find_mount_point.o): In function `find_mount_point':
find_mount_point.c:(.text.find_mount_point+0x46): undefined reference to `setmntent'
find_mount_point.c:(.text.find_mount_point+0xb0): undefined reference to `endmntent'
collect2: ld returned 1 exit status
make: *** [busybox_unstripped] Error 1
```

**Comment by tias** [comment] 2013-01-23 19:43
I compiled the latest busybox successfully yesterday night.

I'll check my setup and try to reproduce yours tonight.

Kind regards,
Tias

**Comment by tias** [comment] 2013-01-23 20:40
Hi,

All of the errors you mention are fixed by other patches (undefined reference to `swapon' for example in 016-swaponoff-syscalls.patch)

The patches depend on each-other so it is not possible to 'cherry-pick' just some patches. 023 is the largest patch number you use, so you have to apply all patches up to 023.
The 050 and 051 patches can be applied separately, hence the larger number.

Sorry if this was unclear, I'll update the docs.

**Closed as completed by tias** 2013-01-23 20:40 UTC

**Comment by dalb8** [comment] 2013-01-23 21:45
Hi. I don't really understand but I'm sure it will be clearer when you update the docs. Also please state which commit at which to apply patches. If this works out I think it'll be good to publish inside stericson's busybox installer. I was thinking , could this work for x86 and MIPS, too?

**Comment by tias** [comment] 2013-01-23 22:10
for x86 and MIPS: yes, I've just merged some commits by Pete Delaney who already implemented that

As to the fix of your problem: when you apply all patches in the patches/\* directory it will work.
Right now it doesn't work because you only applied some of those patches.

Hope this helps; and getting it in stericon's installer would be nice indeed.
Tias

**Comment by dalb8** [comment] 2013-01-24 11:21
I've made an initial sketch which I pushed to fdroiddata. One problem is some of the patches don't work at the latest Tias commit in June e.g.023-etherwake.  The stericson config refers to a commit in March but it has some problems too. Instead of using F-Droid's patching parameter which allows me to write the patches as I want, I would prefer to apply the patches (straight from this repo) in the prebuild using a for loop. Any patching of the patches would then have to be done then with sed.

Side issue is there are other blobs in app/assets in busybox installer app.

**Comment by dalb8** [comment] 2013-04-21 17:41
ARM ok for stericson MIPS has error :`
til-linux/mount.c:2078: warning: implicit declaration of function 'getmntent_r'
util-linux/mount.c:2139: warning: assignment makes pointer from integer without a cast
util-linux/rdate.c: In function 'rdate_main':
util-linux/rdate.c:71: warning: implicit declaration of function 'stime'
util-linux/swaponoff.c: In function 'swap_enable_disable':
util-linux/swaponoff.c:68: warning: implicit declaration of function 'swapon'
util-linux/swaponoff.c:70: warning: implicit declaration of function 'swapoff'
util-linux/swaponoff.c: In function 'do_em_all':
util-linux/swaponoff.c:86: warning: implicit declaration of function 'setmntent'
util-linux/swaponoff.c:86: warning: assignment makes pointer from integer without a cast
util-linux/swaponoff.c:106: warning: implicit declaration of function 'endmntent'
util-linux/umount.c: In function 'umount_main':
util-linux/umount.c:96: warning: implicit declaration of function 'setmntent'
util-linux/umount.c:96: warning: assignment makes pointer from integer without a cast
util-linux/umount.c:101: warning: implicit declaration of function 'getmntent_r'
util-linux/umount.c:111: warning: implicit declaration of function 'endmntent'
In file included from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/machine/endian.h:67,
                 from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/sys/endian.h:40,
                 from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/endian.h:31,
                 from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/byteswap.h:32,
                 from include/platform.h:149,
                 from include/libbb.h:13,
                 from include/busybox.h:8,
                 from applets/applets.c:9:
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/sys/types.h:64: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'nlink_t'
In file included from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/socket.h:29,
                 from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/sys/socket.h:33,
                 from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/netdb.h:66,
                 from include/libbb.h:20,
                 from include/busybox.h:8,
                 from applets/applets.c:9:
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/uio.h:21: error: expected specifier-qualifier-list before '__kernel_size_t'
In file included from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/sys/socket.h:33,
                 from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/netdb.h:66,
                 from include/libbb.h:20,
                 from include/busybox.h:8,
                 from applets/applets.c:9:
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/socket.h:51: error: expected specifier-qualifier-list before '__kernel_size_t'
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/socket.h:58: error: expected specifier-qualifier-list before '__kernel_size_t'
In file included from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/sys/socket.h:33,
                 from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/netdb.h:66,
                 from include/libbb.h:20,
                 from include/busybox.h:8,
                 from applets/applets.c:9:
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/socket.h:84: error: expected declaration specifiers or '...' before '__kernel_size_t'
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/socket.h: In function '__cmsg_nxthdr':
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/socket.h:89: error: 'struct cmsghdr' has no member named 'cmsg_len'
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/socket.h:90: error: '__size' undeclared (first use in this function)
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/socket.h:90: error: (Each undeclared identifier is reported only once
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/socket.h:90: error: for each function it appears in.)
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/socket.h: In function 'cmsg_nxthdr':
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/socket.h:98: error: 'struct msghdr' has no member named 'msg_control'
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/socket.h:98: error: 'struct msghdr' has no member named 'msg_controllen'
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/socket.h:98: error: too many arguments to function '__cmsg_nxthdr'
In file included from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/termios.h:16,
                 from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/termios.h:35,
                 from include/libbb.h:51,
                 from include/busybox.h:8,
                 from applets/applets.c:9:
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/asm/termios.h: At top level:
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/asm/termios.h:24: error: redefinition of 'struct sgttyb'
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/asm/termios.h:32: error: redefinition of 'struct tchars'
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/asm/termios.h:42: error: redefinition of 'struct ltchars'
In file included from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/linux/in.h:209,
                 from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/netinet/in.h:33,
                 from /home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/arpa/inet.h:33,
                 from include/libbb.h:116,
                 from include/busybox.h:8,
                 from applets/applets.c:9:
/home/gerry/android-ndk-r8e/platforms/android-9/arch-mips/usr/include/asm/byteorder.h:37:2: error: #error "MIPS, but neither __MIPSEB__, nor __MIPSEL__???"
make[1]: *** [applets/applets.o] Error 1
make: *** [applets_dir] Error 2
`

Here is recipe: `Build Version:9.6.3,141,26,subdir=trunk/app,srclibs=\
ViewPagerIndicator@2.2.3;Busybox@1_21_0;RootTools@211;\
BusyboxConfigs@e71bc43bd0,prebuild=\
sed -i 's@\(reference.1=\).*@\1$$ViewPagerIndicator$$@' project.properties && \
rm -f ../binaries/* assets/*.png && mkdir -p libs/ && \
cp -r $$RootTools$$ .. && cp -r $$Busybox$$ .. && \
cp -r $$BusyboxConfigs$$/* ../Busybox/configs/ && \
cd ../Busybox && for i in configs/patches/*.patch; do patch -p1 < $i; done && \
mv configs/android_ndk_stericson-like .config,build=\
cd ../RootTools && ant debug && ant -f makejar.ant && \
mv roottools.jar ../app/libs/ && ant clean && \
cd ../Busybox && \
export PATH=$$NDK$$/toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin:\
$$NDK$$/toolchains/mipsel-linux-android-4.4.3/prebuilt/linux-x86/bin:\
$$NDK$$/toolchains/x86-4.4.3/prebuilt/linux-x86/bin:$PATH && \
make CONFIG_SYSROOT="$$NDK$$/platforms/android-9/arch-arm" ARCH=arm ANDROID_NDK=$$NDK$$ && \
cp busybox ../binaries/busybox-1.20-arm && \
mv busybox ../app/assets/busybox1.20.1.png && make clean && \
make CONFIG_SYSROOT="$$NDK$$/platforms/android-9/arch-mips" ARCH=mips ANDROID_NDK=$$NDK$$ && \
mv busybox ../binaries/busybox-1.20-mips && make clean && \
make CONFIG_SYSROOT="$$NDK$$/platforms/android-9/arch-x86" ARCH=x86 ANDROID_NDK=$$NDK$$ && \
mv busybox ../binaries/busybox-1.20-x86 && make clean
`

**Comment by cielavenir** [comment] 2015-04-21 07:50
Hi.
I had similar problem. I used busybox-1.21.0.tar.bz2 but I failed.
I used https://github.com/tias/android-busybox-ndk/commit/c9677ed83c948c9afb7f1bbd9bac91c854289887 zipball to successful build.
But I cannot find the head of this repo. Where is it?

**Comment by cielavenir** [comment] 2015-04-21 07:53
Sorry to raise old thread, but I'm asking I cannot find any other implementation of ether-wake...
